// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: base.grpc/agent.proto/proto.proto

package gRPC_agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentClient interface {
	SendDataHTTP(ctx context.Context, in *DataFromHttpResponse, opts ...grpc.CallOption) (*ResponseAgent, error)
	SendDataDOM(ctx context.Context, in *DataDOM, opts ...grpc.CallOption) (*ResponseAgent, error)
	SendActionDOM(ctx context.Context, in *ActionDOM, opts ...grpc.CallOption) (*ResponseAgent, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) SendDataHTTP(ctx context.Context, in *DataFromHttpResponse, opts ...grpc.CallOption) (*ResponseAgent, error) {
	out := new(ResponseAgent)
	err := c.cc.Invoke(ctx, "/BasegRPC.Agent/SendDataHTTP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) SendDataDOM(ctx context.Context, in *DataDOM, opts ...grpc.CallOption) (*ResponseAgent, error) {
	out := new(ResponseAgent)
	err := c.cc.Invoke(ctx, "/BasegRPC.Agent/SendDataDOM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) SendActionDOM(ctx context.Context, in *ActionDOM, opts ...grpc.CallOption) (*ResponseAgent, error) {
	out := new(ResponseAgent)
	err := c.cc.Invoke(ctx, "/BasegRPC.Agent/SendActionDOM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility
type AgentServer interface {
	SendDataHTTP(context.Context, *DataFromHttpResponse) (*ResponseAgent, error)
	SendDataDOM(context.Context, *DataDOM) (*ResponseAgent, error)
	SendActionDOM(context.Context, *ActionDOM) (*ResponseAgent, error)
	
}

// UnimplementedAgentServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (UnimplementedAgentServer) SendDataHTTP(context.Context, *DataFromHttpResponse) (*ResponseAgent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDataHTTP not implemented")
}
func (UnimplementedAgentServer) SendDataDOM(context.Context, *DataDOM) (*ResponseAgent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDataDOM not implemented")
}
func (UnimplementedAgentServer) SendActionDOM(context.Context, *ActionDOM) (*ResponseAgent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendActionDOM not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_SendDataHTTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataFromHttpResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).SendDataHTTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BasegRPC.Agent/SendDataHTTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).SendDataHTTP(ctx, req.(*DataFromHttpResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_SendDataDOM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataDOM)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).SendDataDOM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BasegRPC.Agent/SendDataDOM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).SendDataDOM(ctx, req.(*DataDOM))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_SendActionDOM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionDOM)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).SendActionDOM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BasegRPC.Agent/SendActionDOM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).SendActionDOM(ctx, req.(*ActionDOM))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BasegRPC.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendDataHTTP",
			Handler:    _Agent_SendDataHTTP_Handler,
		},
		{
			MethodName: "SendDataDOM",
			Handler:    _Agent_SendDataDOM_Handler,
		},
		{
			MethodName: "SendActionDOM",
			Handler:    _Agent_SendActionDOM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base.grpc/agent.proto/proto.proto",
}
